name: CheckAfk
version: '${version}'
main: newblock.checkafk.CheckAfk
softdepend: [PlaceholderAPI]
commands:
  checkafk:
    usage: /checkafk reload
    permission: checkafk.reload
    description: 重新载入配置文件
permissions:
  checkafk.reload:
    default: op
  checkafk.bypass:
    default: false