name: CheckAfk
version: '${version}'
main: newblock.checkafk.CheckAfk
softdepend: [PlaceholderAPI]
commands:
  checkafk:
    usage: |
      /checkafk reload - 重新载入配置文件
      /checkafk time <minutes> - 设置AFK检查时间(分钟)
      /checkafk reset - 重置AFK检查时间为默认值
    permission: checkafk.use
    description: CheckAFK插件主命令
permissions:
  checkafk.use:
    default: true
  checkafk.reload:
    default: op
  checkafk.time:
    default: true
  checkafk.reset:
    default: op
  checkafk.bypass:
    default: false